### ISSUE TITLE
Install Error!

### ISSUE THREAD

**Issue by Hello-Linux** [xuthus5/fedora-sogou-pinyin#2]
open file /usr/share/fcitx-sogoupinyin/SogouInput/sgim_charvalid.bin failed.                                                                  
没有那个文件或目录: 没有那个文件或目录
没有那个文件或目录: 没有那个文件或目录
open file /root/.config/SogouPY/punctures.ini failed.
没有那个文件或目录: 没有那个文件或目录
check false, remove P
没有那个文件或目录: 没有那个文件或目录
没有那个文件或目录: 没有那个文件或目录
没有那个文件或目录: 没有那个文件或目录
没有那个文件或目录: 没有那个文件或目录
没有那个文件或目录: 没有那个文件或目录
open file /root/.config/SogouPY/punctures.ini failed.
没有那个文件或目录: 没有那个文件或目录
open file  failed.
没有那个文件或目录: 没有那个文件或目录
check false, remove C
没有那个文件或目录: 没有那个文件或目录
open file  failed.
没有那个文件或目录: 没有那个文件或目录
check false, remove C
没有那个文件或目录: 没有那个文件或目录
open file /root/.config/SogouPY/sgim_usr_v3_ext.bin failed.
没有那个文件或目录: 没有那个文件或目录
check false, remove U
没有那个文件或目录: 没有那个文件或目录
没有那个文件或目录: 没有那个文件或目录
open file /root/.config/SogouPY/sgim_del_word.bin failed.
没有那个文件或目录: 没有那个文件或目录
check false, remove D
没有那个文件或目录: 没有那个文件或目录
没有那个文件或目录: 没有那个文件或目录
open file /root/.config/SogouPY/sgim_phrases.bin failed.
没有那个文件或目录: 没有那个文件或目录
check false, remove A
没有那个文件或目录: 没有那个文件或目录
没有那个文件或目录: 没有那个文件或目录
open file /root/.config/SogouPY/sgim_uspm.bin failed.
没有那个文件或目录: 没有那个文件或目录
check false, remove U
没有那个文件或目录: 没有那个文件或目录
没有那个文件或目录: 没有那个文件或目录
open file /root/.config/SogouPY/sgim_privilege.bin failed.
没有那个文件或目录: 没有那个文件或目录
check false, remove P
没有那个文件或目录: 没有那个文件或目录
没有那个文件或目录: 没有那个文件或目录
open file /root/.config/SogouPY/sgim_eng_usr.bin failed.
没有那个文件或目录: 没有那个文件或目录
check false, remove E
没有那个文件或目录: 没有那个文件或目录
没有那个文件或目录: 没有那个文件或目录
open file /root/.config/SogouPY/sgim_url_usr.bin failed.
没有那个文件或目录: 没有那个文件或目录
check false, remove U
没有那个文件或目录: 没有那个文件或目录
没有那个文件或目录: 没有那个文件或目录
open file /root/.config/SogouPY/sgim_keymap.bin failed.
没有那个文件或目录: 没有那个文件或目录
check false, remove K
没有那个文件或目录: 没有那个文件或目录
没有那个文件或目录: 没有那个文件或目录
没有那个文件或目录: 没有那个文件或目录
Can not lock /tmp/sogou-qimpanel:0.pid: 资源暂时不可用.

**Comment by xuthus5** [comment]
不更新sogou.tar.xz包没有问题。

**Comment by xuthus5** [comment]
更新sogou版本，请用dpkg -X 解压缩 deb包，然后打包usr/ 和 /etc替换sogou.tar.xz 再自行测试。

**Comment by Hello-Linux** [comment]
@xuthus5  我没有更新sogou.tar.xz呀，安装总是报错，我是fedora30 版本，你的意思是让我更新sogou版本？

**Comment by Hello-Linux** [comment]
@xuthus5  我已经在fredora上安装了好几次了都不管用。我感觉是你的安装程序出了问题，你自己在fedora30上测试过么？
```
open file /usr/share/fcitx-sogoupinyin/SogouInput/sgim_charvalid.bin failed.
没有那个文件或目录: 没有那个文件或目录
没有那个文件或目录: 没有那个文件或目录
open file /root/.config/SogouPY/punctures.ini failed.                                                                                                         
没有那个文件或目录: 没有那个文件或目录
check false, remove P
没有那个文件或目录: 没有那个文件或目录
没有那个文件或目录: 没有那个文件或目录
没有那个文件或目录: 没有那个文件或目录
没有那个文件或目录: 没有那个文件或目录
没有那个文件或目录: 没有那个文件或目录
open file /root/.config/SogouPY/punctures.ini failed.
没有那个文件或目录: 没有那个文件或目录
open file  failed.
没有那个文件或目录: 没有那个文件或目录
check false, remove C
没有那个文件或目录: 没有那个文件或目录
open file  failed.
没有那个文件或目录: 没有那个文件或目录
check false, remove C
没有那个文件或目录: 没有那个文件或目录
open file /root/.config/SogouPY/sgim_usr_v3_ext.bin failed.
没有那个文件或目录: 没有那个文件或目录
check false, remove U
没有那个文件或目录: 没有那个文件或目录
没有那个文件或目录: 没有那个文件或目录
open file /root/.config/SogouPY/sgim_del_word.bin failed.
没有那个文件或目录: 没有那个文件或目录
check false, remove D
没有那个文件或目录: 没有那个文件或目录
没有那个文件或目录: 没有那个文件或目录
open file /root/.config/SogouPY/sgim_phrases.bin failed.
没有那个文件或目录: 没有那个文件或目录
check false, remove A
没有那个文件或目录: 没有那个文件或目录
没有那个文件或目录: 没有那个文件或目录
open file /root/.config/SogouPY/sgim_uspm.bin failed.
没有那个文件或目录: 没有那个文件或目录
check false, remove U
没有那个文件或目录: 没有那个文件或目录
没有那个文件或目录: 没有那个文件或目录
open file /root/.config/SogouPY/sgim_privilege.bin failed.
没有那个文件或目录: 没有那个文件或目录
check false, remove P
没有那个文件或目录: 没有那个文件或目录
没有那个文件或目录: 没有那个文件或目录
open file /root/.config/SogouPY/sgim_eng_usr.bin failed.
没有那个文件或目录: 没有那个文件或目录
check false, remove E
没有那个文件或目录: 没有那个文件或目录
没有那个文件或目录: 没有那个文件或目录
open file /root/.config/SogouPY/sgim_url_usr.bin failed.
没有那个文件或目录: 没有那个文件或目录
check false, remove U
没有那个文件或目录: 没有那个文件或目录
没有那个文件或目录: 没有那个文件或目录
open file /root/.config/SogouPY/sgim_keymap.bin failed.
没有那个文件或目录: 没有那个文件或目录
check false, remove K
没有那个文件或目录: 没有那个文件或目录
没有那个文件或目录: 没有那个文件或目录
没有那个文件或目录: 没有那个文件或目录

gnome-shell:1894
    /opt/fedora-sogou-pinyin    master !3 ?2  Could not parse application stylesheetrnetes-admin-c52a2452dbc28495f9b909786e0de661a ⎈  root@localhost 
(WARN-3676 fcitx-config.c:922) Invalid Entry: line 150 missing '='
(WARN-3676 fcitx-config.c:922) Invalid Entry: line 150 missing '='
(WARN-3676 fcitx-config.c:922) Invalid Entry: line 152 missing '='
(WARN-3676 fcitx-config.c:922) Invalid Entry: line 150 missing '='
(WARN-3676 fcitx-config.c:922) Invalid Entry: line 148 missing '='
(WARN-3676 fcitx-config.c:922) Invalid Entry: line 152 missing '='
(WARN-3676 fcitx-config.c:922) Invalid Entry: line 150 missing '='
(WARN-3676 fcitx-config.c:922) Invalid Entry: line 150 missing '='
(WARN-3676 fcitx-config.c:922) Invalid Entry: line 150 missing '='
(WARN-3676 fcitx-config.c:922) Invalid Entry: line 152 missing '='
(WARN-3676 fcitx-config.c:922) Invalid Entry: line 154 missing '='
(WARN-3676 fcitx-config.c:922) Invalid Entry: line 152 missing '='
open file /root/.config/SogouPY/sgim_phrases.bin failed.
没有那个文件或目录: 没有那个文件或目录
"sni-qt/3676" WARN  11:00:57.805 void StatusNotifierItemFactory::connectToSnw() Invalid interface to SNW_SERVICE
```

**Comment by xuthus5** [comment]
测试fedora31-GNOME并未出现如你所述的问题。
![fedora-sougou-test.png](https://i.loli.net/2020/04/10/hRDib4gvaZ5kuET.png)

**Comment by xuthus5** [comment]
fedora30-GNOME测试结果
`./install.sh install` 执行后
![installed.png](https://i.loli.net/2020/04/10/IwzGxE4JhFoLkjD.png)

测试结果
![test.png](https://i.loli.net/2020/04/10/Xa4CLDxpcwvTQ8S.png)

**Comment by Hello-Linux** [comment]
我看看了一下我的版本是Fedora release 31 (Thirty One)，为啥我安装不成功呢？

**Comment by Hello-Linux** [comment]
cp: 无法创建普通文件'/usr/bin/sogou-qimpanel': 文本文件忙
ln: 无法创建符号链接 '/usr/lib64/fcitx-punc-ng.so': 文件已存在
ln: 无法创建符号链接 '/usr/lib64/libidn.so.11': 文件已存在
open file /usr/share/fcitx-sogoupinyin/SogouInput/sgim_charvalid.bin failed.
没有那个文件或目录: 没有那个文件或目录
没有那个文件或目录: 没有那个文件或目录
open file /root/.config/SogouPY/punctures.ini failed.
没有那个文件或目录: 没有那个文件或目录
check false, remove P
没有那个文件或目录: 没有那个文件或目录
没有那个文件或目录: 没有那个文件或目录
没有那个文件或目录: 没有那个文件或目录
没有那个文件或目录: 没有那个文件或目录
没有那个文件或目录: 没有那个文件或目录
open file /root/.config/SogouPY/punctures.ini failed.
没有那个文件或目录: 没有那个文件或目录
open file  failed.
没有那个文件或目录: 没有那个文件或目录
check false, remove C
没有那个文件或目录: 没有那个文件或目录
open file  failed.
没有那个文件或目录: 没有那个文件或目录
check false, remove C
没有那个文件或目录: 没有那个文件或目录
open file /root/.config/SogouPY/sgim_usr_v3_ext.bin failed.
没有那个文件或目录: 没有那个文件或目录
check false, remove U
没有那个文件或目录: 没有那个文件或目录
没有那个文件或目录: 没有那个文件或目录
open file /root/.config/SogouPY/sgim_del_word.bin failed.
没有那个文件或目录: 没有那个文件或目录
check false, remove D
没有那个文件或目录: 没有那个文件或目录
没有那个文件或目录: 没有那个文件或目录
open file /root/.config/SogouPY/sgim_phrases.bin failed.
没有那个文件或目录: 没有那个文件或目录
check false, remove A
没有那个文件或目录: 没有那个文件或目录
没有那个文件或目录: 没有那个文件或目录
open file /root/.config/SogouPY/sgim_uspm.bin failed.                                                                                                         
没有那个文件或目录: 没有那个文件或目录
check false, remove U
没有那个文件或目录: 没有那个文件或目录
没有那个文件或目录: 没有那个文件或目录
open file /root/.config/SogouPY/sgim_privilege.bin failed.
没有那个文件或目录: 没有那个文件或目录
check false, remove P
没有那个文件或目录: 没有那个文件或目录
没有那个文件或目录: 没有那个文件或目录
open file /root/.config/SogouPY/sgim_eng_usr.bin failed.
没有那个文件或目录: 没有那个文件或目录
check false, remove E
没有那个文件或目录: 没有那个文件或目录
没有那个文件或目录: 没有那个文件或目录
open file /root/.config/SogouPY/sgim_url_usr.bin failed.
没有那个文件或目录: 没有那个文件或目录
check false, remove U
没有那个文件或目录: 没有那个文件或目录
没有那个文件或目录: 没有那个文件或目录
open file /root/.config/SogouPY/sgim_keymap.bin failed.
没有那个文件或目录: 没有那个文件或目录
check false, remove K
没有那个文件或目录: 没有那个文件或目录
没有那个文件或目录: 没有那个文件或目录
没有那个文件或目录: 没有那个文件或目录

**Comment by xuthus5** [comment]
建议手动执行安装。
解包搜狗输入法
将包下的 etc/和 usr/目录放置根目录下。
cp -pr usr/ /
cp -pr etc/ /

链接共享库
cp /usr/lib/x86_64-linux-gnu/fcitx/fcitx-sogoupinyin.so /usr/lib64/fcitx
ln -s /usr/lib/x86_64-linux-gnu/fcitx/fcitx-punc-ng.so /usr/lib64/fcitx-punc-ng.so
ln -s /usr/lib64/libidn.so.12 /usr/lib64/libidn.so.11

启动
sogou-qimpanel

启动且无致命错误后，可以测试输入法，或者终止安装程序。

**Comment by Hello-Linux** [comment]
手动安装也失败了
运行这个命令提示
![2020-04-10 14-50-37 的屏幕截图](https://user-images.githubusercontent.com/17851645/78969921-b8fb0680-7b3a-11ea-91d3-50b85de4f0e7.png)

**Comment by Hello-Linux** [comment]
加我QQ吧: 752258985

**Comment by xuthus5** [comment]
先安装依赖。dnf install -y qtwebkit libidn-devel

**Comment by Hello-Linux** [comment]
安装完成后我运行这个命令还是提示这些错误
```
open file /usr/share/fcitx-sogoupinyin/SogouInput/sgim_charvalid.bin failed.                                                                                  
没有那个文件或目录: 没有那个文件或目录
没有那个文件或目录: 没有那个文件或目录
open file /root/.config/SogouPY/punctures.ini failed.
没有那个文件或目录: 没有那个文件或目录
check false, remove P
没有那个文件或目录: 没有那个文件或目录
没有那个文件或目录: 没有那个文件或目录
没有那个文件或目录: 没有那个文件或目录
没有那个文件或目录: 没有那个文件或目录
没有那个文件或目录: 没有那个文件或目录
open file /root/.config/SogouPY/punctures.ini failed.
没有那个文件或目录: 没有那个文件或目录
open file  failed.
没有那个文件或目录: 没有那个文件或目录
check false, remove C
没有那个文件或目录: 没有那个文件或目录
open file  failed.
没有那个文件或目录: 没有那个文件或目录
check false, remove C
没有那个文件或目录: 没有那个文件或目录
open file /root/.config/SogouPY/sgim_usr_v3_ext.bin failed.
没有那个文件或目录: 没有那个文件或目录
check false, remove U
没有那个文件或目录: 没有那个文件或目录
没有那个文件或目录: 没有那个文件或目录
open file /root/.config/SogouPY/sgim_del_word.bin failed.
没有那个文件或目录: 没有那个文件或目录
check false, remove D
没有那个文件或目录: 没有那个文件或目录
没有那个文件或目录: 没有那个文件或目录
open file /root/.config/SogouPY/sgim_phrases.bin failed.
没有那个文件或目录: 没有那个文件或目录
check false, remove A
没有那个文件或目录: 没有那个文件或目录
没有那个文件或目录: 没有那个文件或目录
open file /root/.config/SogouPY/sgim_uspm.bin failed.
没有那个文件或目录: 没有那个文件或目录
check false, remove U
没有那个文件或目录: 没有那个文件或目录
没有那个文件或目录: 没有那个文件或目录
open file /root/.config/SogouPY/sgim_privilege.bin failed.
没有那个文件或目录: 没有那个文件或目录
check false, remove P
没有那个文件或目录: 没有那个文件或目录
没有那个文件或目录: 没有那个文件或目录
open file /root/.config/SogouPY/sgim_eng_usr.bin failed.
没有那个文件或目录: 没有那个文件或目录
check false, remove E
没有那个文件或目录: 没有那个文件或目录
没有那个文件或目录: 没有那个文件或目录
open file /root/.config/SogouPY/sgim_url_usr.bin failed.
没有那个文件或目录: 没有那个文件或目录
check false, remove U
没有那个文件或目录: 没有那个文件或目录
没有那个文件或目录: 没有那个文件或目录
open file /root/.config/SogouPY/sgim_keymap.bin failed.
没有那个文件或目录: 没有那个文件或目录
check false, remove K
没有那个文件或目录: 没有那个文件或目录
没有那个文件或目录: 没有那个文件或目录
没有那个文件或目录: 没有那个文件或目录
```

**Comment by xuthus5** [comment]
缓存和配置问题？删除你的配置文件重试看看
rm -rf ~/.config/SogouPY 
rm -rf /tmp./sogou*
rm -rf /tmp/fcitx-socket-:0

**Comment by Hello-Linux** [comment]
上面三个步骤都执行了还是不行，我想放弃搜狗输入法！！！

**Comment by Hello-Linux** [comment]
可以使用了！，我重启了一下电脑就可以使用了。。。。。。

**Comment by Hello-Linux** [comment]
我再去试试官方的最新版可以使用么

**Comment by Hello-Linux** [comment]
@xuthus5  新版提示: load qt_zh_CN.qm error.

**Comment by Hello-Linux** [comment]
@xuthus5  最新版也可以使用了，皮肤我怎么切换呢？
